# Generated by Django 5.0.6 on 2024-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('vip', 'В работе'), ('done', 'Завершен(а)'), ('JR', 'Требуется исправления')], max_length=4, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
