# Generated by Django 5.0.6 on 2024-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
