# Generated by Django 5.0.6 on 2024-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_description_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Описанние'),
            preserve_default=False,
        ),
    ]
