# Generated by Django 5.0.6 on 2024-05-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_description_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(default='', upload_to='uploads/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
